# Support the development of this regex parser library
# This file configures funding platforms to help support open-source development

# GitHub Sponsors - Sponsor this project directly on GitHub
github: yoeunes

# One-time or recurring support
custom:
  - https://www.paypal.com/paypalme/yoeunes
