<?php

declare(strict_types=1);

$header = <<<'EOF'
This file is part of the RegexParser package.
 
(c) Younes ENNAJI <younes.ennaji.pro@gmail.com>
 
For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
EOF;

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    ->exclude([
        '.cache/',
        'tools/',
        'vendor/',
    ])
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setParallelConfig(PhpCsFixer\Runner\Parallel\ParallelConfigFactory::detect())
    ->setRules([
        '@PSR12'                                  => true,
        '@PSR12:risky'                            => true,
        '@Symfony'                                => true,
        '@Symfony:risky'                          => true,
        '@PHPUnit10x0Migration:risky'             => true,
        'header_comment'                          => ['header' => $header],
        'declare_strict_types'                    => true,
        'ordered_class_elements'                  => true,
        'ordered_interfaces'                      => true,
        'ordered_traits'                          => true,
        'php_unit_construct'                      => true,
        'php_unit_dedicate_assert'                => true,
        'php_unit_dedicate_assert_internal_type'  => true,
        'php_unit_mock'                           => true,
        'php_unit_mock_short_will_return'         => true,
        'php_unit_strict'                         => true,
        'php_unit_test_case_static_method_calls'  => false,
        'phpdoc_add_missing_param_annotation'     => true,
        'phpdoc_line_span'                        => true,
        'phpdoc_order'                            => true,
        'phpdoc_scalar'                           => true,
        'phpdoc_single_line_var_spacing'          => true,
        'phpdoc_summary'                          => false,
        'phpdoc_var_annotation_correct_order'     => true,
        'phpdoc_var_without_name'                 => true,
        'protected_to_private'                    => true,
        'semicolon_after_instruction'             => true,
        'single_line_throw'                       => false,
        'single_trait_insert_per_statement'       => true,
        'strict_comparison'                       => true,
        'strict_param'                            => true,
        'ternary_to_null_coalescing'              => true,
        'trailing_comma_in_multiline'             => ['elements' => ['arguments']],
        'unary_operator_spaces'                   => true,
        'phpdoc_to_comment'                       => true,
        'array_indentation'                       => true,
        'blank_line_after_namespace'              => true,
        'blank_line_after_opening_tag'            => true,
        'blank_line_before_statement'             => true,
        'blank_line_between_import_groups'        => true,
        'blank_lines_before_namespace'            => true,
        'cast_spaces'                             => true,
        'class_definition'                        => [
            'multi_line_extends_each_single_line' => true,
            'single_item_single_line'             => true,
            'single_line'                         => true,
        ],
        'clean_namespace'                         => true,
        'compact_nullable_type_declaration'       => true,
        'concat_space'                            => ['spacing' => 'none'],
        'constant_case'                           => ['case' => 'lower'],
        'control_structure_braces'                => true,
        'control_structure_continuation_position' => ['position' => 'same_line'],
        'declare_equal_normalize'                 => true,
        'declare_parentheses'                     => true,
        'elseif'                                  => true,
        'encoding'                                => true,
        'full_opening_tag'                        => true,
        'fully_qualified_strict_types'            => false,
        'function_declaration'                    => true,
        'general_phpdoc_tag_rename'               => true,
        'include'                                 => true,
        'increment_style'                         => ['style' => 'post'],
        'indentation_type'                        => true,
        'integer_literal_case'                    => true,
        'lambda_not_used_import'                  => true,
        'line_ending'                             => true,
        'linebreak_after_opening_tag'             => true,
        'list_syntax'                             => true,
        'lowercase_cast'                          => true,
        'lowercase_keywords'                      => true,
        'lowercase_static_reference'              => true,
        'magic_constant_casing'                   => true,
        'magic_method_casing'                     => true,
        'method_chaining_indentation'             => false,
        'multiline_whitespace_before_semicolons'  => ['strategy' => 'no_multi_line'],
        'native_function_casing'                  => true,
        'native_type_declaration_casing'          => true,
        'no_alias_language_construct_call'        => true,
        'no_alternative_syntax'                   => true,
        'no_binary_string'                        => true,
        'no_blank_lines_after_class_opening'      => true,
        'no_blank_lines_after_phpdoc'             => true,
        'no_closing_tag'                          => true,
        'no_empty_phpdoc'                         => true,
        'no_empty_statement'                      => true,
        'no_extra_blank_lines'                    => ['tokens' => ['extra', 'throw', 'use']],
        'no_leading_import_slash' => true,
        'no_leading_namespace_whitespace' => true,
        'no_mixed_echo_print' => ['use' => 'echo'],
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_multiple_statements_per_line' => true,
        'no_short_bool_cast' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_space_around_double_colon' => true,
        'no_spaces_after_function_name' => true,
        'no_spaces_around_offset' => ['positions' => ['inside', 'outside']],
        'no_trailing_comma_in_singleline' => true,
        'no_trailing_whitespace' => true,
        'no_trailing_whitespace_in_comment' => true,
        'no_unneeded_control_parentheses' => ['statements' => ['break', 'clone', 'continue', 'echo_print', 'return', 'switch_case', 'yield']],
        'no_unneeded_braces' => true,
        'no_unset_cast' => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line' => true,
        'normalize_index_brace' => true,
        'nullable_type_declaration' => true,
        'object_operator_without_whitespace' => true,
        'ordered_imports' => ['sort_algorithm' => 'alpha', 'imports_order' => ['const', 'class', 'function']],
        'php_unit_method_casing' => ['case' => 'snake_case'],
        'php_unit_set_up_tear_down_visibility' => true,
        'phpdoc_indent' => true,
        'phpdoc_inline_tag_normalizer' => true,
        'phpdoc_no_access' => true,
        'phpdoc_no_package' => true,
        'phpdoc_no_useless_inheritdoc' => true,
        'phpdoc_trim' => true,
        'phpdoc_types' => true,
        'psr_autoloading' => false,
        'return_type_declaration' => ['space_before' => 'none'],
    ])
    ->setFinder($finder)
    ->setCacheFile('.cache/php-cs-fixer/cache.json');
