path:
    - .php-cs-fixer.dist.php
    - rector.php
    - bin/regex
    - src/
    - tests/
    - benchmarks/

exclude:
    - Fixtures/

jobs: 10

extensions:
    - php

cache-dir: .cache/phplint/

warning: true
