<?php

declare(strict_types=1);

/*
 * This file is part of the RegexParser package.
 *
 * (c) Younes ENNAJI <younes.ennaji.pro@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace RegexParser\Tests\Integration;

use PHPUnit\Framework\TestCase;
use RegexParser\Exception\LexerException;
use RegexParser\Lexer;
use RegexParser\TokenType;

class LexerCommentTest extends TestCase
{
    /**
     * Tests an empty comment (?#)
     */
    public function test_lexer_empty_comment(): void
    {
        $tokens = new Lexer()->tokenize('/(?#)/')->getTokens();

        // Must contain: /, (?#, ), /, EOF
        $this->assertCount(5, $tokens);
        $this->assertSame(TokenType::T_COMMENT_OPEN, $tokens[1]->type);
        $this->assertSame(TokenType::T_GROUP_CLOSE, $tokens[2]->type);
    }

    /**
     * Tests an unclosed comment at the end of the string.
     * Covers: "if ($this->inCommentMode) { throw ... }" in tokenize()
     * and the end-of-string logic in consumeCommentMode().
     */
    public function test_lexer_unclosed_comment_at_eof(): void
    {
        $this->expectException(LexerException::class);
        $this->expectExceptionMessage('Unclosed comment ")" at end of input');

        new Lexer()->tokenize('/(?#oups')->getTokens();
    }

    /**
     * Tests the content of a comment.
     */
    public function test_lexer_comment_content(): void
    {
        $tokens = new Lexer()->tokenize('/(?# hello world )/')->getTokens();

        // Token 0: /
        // Token 1: (?#
        // Token 2: hello world (T_LITERAL generated by consumeCommentMode)
        // Token 3: )

        $this->assertSame(' hello world ', $tokens[2]->value);
    }
}
