<?php

declare(strict_types=1);

/*
 * This file is part of the RegexParser package.
 *
 * (c) Younes ENNAJI <younes.ennaji.pro@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace RegexParser;

use RegexParser\Exception\ParserException;
use RegexParser\Exception\RecursionLimitException;
use RegexParser\Exception\ResourceLimitException;

/**
 * The Parser.
 *
 * It transforms a stream of Tokens (from the Lexer) into an Abstract Syntax Tree (AST).
 * It implements a Recursive Descent Parser based on PCRE grammar.
 *
 * The Parser is independent of the Lexer and operates purely on a TokenStream.
 * Use the Regex class for convenient string-based parsing that handles
 * delimiter extraction, tokenization, and parsing automatically.
 */
class Parser
{
    /**
     * Token stream (replaces array of tokens for memory efficiency).
     */
    private TokenStream $stream;

    /**
     * Transforms a `TokenStream` into a structured Abstract Syntax Tree (AST).
     *
     * Purpose: This is the main entry point of the `Parser`. Its role is to consume the
     * flat list of tokens produced by the `Lexer` and organize them into a hierarchical
     * `RegexNode` tree that represents the logical structure of the regular expression.
     * This AST is the foundation upon which all other analysis, compilation, and
     * manipulation visitors operate. As a contributor, this is where you would start
     * to understand how the library interprets the token sequence.
     *
     * The parser uses a recursive descent strategy, with methods like `parseAlternation`
     * and `parseSequence` corresponding to the rules of the regex grammar.
     *
     * @param TokenStream $stream        the sequence of tokens generated by the `Lexer`
     * @param string      $flags         The regex flags (e.g., 'i', 'ms') that apply to the pattern.
     * @param string      $delimiter     The delimiter character (e.g., '/') used in the original regex string.
     * @param int         $patternLength the byte length of the original pattern string (used for root node metadata)
     *
     * @throws ParserException         If the token stream represents an invalid sequence according to the regex grammar
     *                                 (e.g., an unclosed group, a quantifier without a target).
     * @throws RecursionLimitException if the pattern is deeply nested and exceeds internal recursion limits
     * @throws ResourceLimitException  if the pattern is excessively large and exceeds node count limits
     *
     * @return Node\RegexNode the root node of the fully constructed AST
     *
     * @example
     * ```php
     * $lexer = new Lexer();
     * $tokenStream = $lexer->tokenize('a|b');
     *
     * $parser = new Parser();
     * $ast = $parser->parse($tokenStream, 'i', '/', 3);
     * // $ast is now a RegexNode containing an AlternationNode.
     * ```
     */
    public function parse(TokenStream $stream, string $flags = '', string $delimiter = '/', int $patternLength = 0): Node\RegexNode
    {
        // Set the stream for parsing
        $this->stream = $stream;

        // Parse the pattern content
        $patternNode = $this->parseAlternation();

        // Ensure we reached the end of the pattern
        $this->consume(TokenType::T_EOF, 'Unexpected content at end of pattern');

        return new Node\RegexNode($patternNode, $flags, $delimiter, 0, $patternLength);
    }

    /**
     * alternation -> sequence ( "|" sequence )*
     */
    private function parseAlternation(): Node\NodeInterface
    {
        $startPos = $this->current()->position;
        $nodes = [$this->parseSequence()];

        while ($this->match(TokenType::T_ALTERNATION)) {
            $nodes[] = $this->parseSequence();
        }

        if (1 === \count($nodes)) {
            return $nodes[0];
        }

        // Calculate end position based on the last node
        $endPos = end($nodes)->getEndPosition();

        return new Node\AlternationNode($nodes, $startPos, $endPos);
    }

    /**
     * sequence -> quantifiedAtom*
     */
    private function parseSequence(): Node\NodeInterface
    {
        $nodes = [];
        $startPos = $this->current()->position;

        while (!$this->isAtEnd()
            && !$this->check(TokenType::T_GROUP_CLOSE)
            && !$this->check(TokenType::T_ALTERNATION)
        ) {
            // Handle silent tokens (Quote Mode)
            if ($this->match(TokenType::T_QUOTE_MODE_START) || $this->match(TokenType::T_QUOTE_MODE_END)) {
                continue;
            }

            $nodes[] = $this->parseQuantifiedAtom();
        }

        if (empty($nodes)) {
            // "Empty" node at the current position
            return new Node\LiteralNode('', $startPos, $startPos);
        }

        if (1 === \count($nodes)) {
            return $nodes[0];
        }

        $endPos = end($nodes)->getEndPosition();

        return new Node\SequenceNode($nodes, $startPos, $endPos);
    }

    /**
     * quantifiedAtom -> atom ( QUANTIFIER )?
     */
    private function parseQuantifiedAtom(): Node\NodeInterface
    {
        $node = $this->parseAtom();

        if ($this->match(TokenType::T_QUANTIFIER)) {
            $token = $this->previous();

            // Validation: Quantifier on empty literal
            if ($node instanceof Node\LiteralNode && '' === $node->value) {
                throw new ParserException(\sprintf('Quantifier without target at position %d', $token->position));
            }

            // Validation: Quantifier on empty group sequence
            if ($node instanceof Node\GroupNode) {
                $child = $node->child;
                if (($child instanceof Node\LiteralNode && '' === $child->value)
                    || ($child instanceof Node\SequenceNode && empty($child->children))) {
                    throw new ParserException(\sprintf('Quantifier without target at position %d', $token->position));
                }
            }

            // Validation: Assertions, anchors, and verbs cannot be quantified
            if ($node instanceof Node\AnchorNode || $node instanceof Node\AssertionNode || $node instanceof Node\PcreVerbNode || $node instanceof Node\KeepNode) {
                $nodeName = match (true) {
                    $node instanceof Node\AnchorNode => $node->value,
                    $node instanceof Node\AssertionNode => '\\'.$node->value,
                    $node instanceof Node\PcreVerbNode => '(*'.$node->verb.')',
                    default => '\K',
                };

                throw new ParserException(
                    \sprintf('Quantifier "%s" cannot be applied to assertion or verb "%s" at position %d', $token->value, $nodeName, $node->getStartPosition()));
            }

            [$quantifier, $type] = $this->parseQuantifierValue($token->value);

            $startPos = $node->getStartPosition();
            $endPos = $token->position + mb_strlen($token->value);

            return new Node\QuantifierNode($node, $quantifier, $type, $startPos, $endPos);
        }

        return $node;
    }

    /**
     * @return array{0: string, 1: Node\QuantifierType}
     */
    private function parseQuantifierValue(string $value): array
    {
        $lastChar = substr($value, -1);
        $baseValue = substr($value, 0, -1);

        if ('?' === $lastChar && \strlen($value) > 1) {
            return [$baseValue, Node\QuantifierType::T_LAZY];
        }

        if ('+' === $lastChar && \strlen($value) > 1) {
            return [$baseValue, Node\QuantifierType::T_POSSESSIVE];
        }

        return [$value, Node\QuantifierType::T_GREEDY];
    }

    /**
     * atom -> T_LITERAL | T_CHAR_TYPE | ...
     */
    private function parseAtom(): Node\NodeInterface
    {
        $token = $this->current();
        $startPos = $token->position;

        // Comments (emitted by Lexer) must be parsed into CommentNode
        if ($this->match(TokenType::T_COMMENT_OPEN)) {
            return $this->parseComment();
        }

        // Quote Mode markers might leak here if sequence parsing logic didn't catch them all.
        // We consume them silently and recurse to get the next real atom.
        if ($this->match(TokenType::T_QUOTE_MODE_START) || $this->match(TokenType::T_QUOTE_MODE_END)) {
            return $this->parseAtom();
        }

        if ($this->match(TokenType::T_LITERAL)) {
            $token = $this->previous();
            $endPos = $startPos + mb_strlen($token->value);

            return new Node\LiteralNode($token->value, $startPos, $endPos);
        }

        if ($this->match(TokenType::T_LITERAL_ESCAPED)) {
            $token = $this->previous();
            $endPos = $startPos + mb_strlen($token->value) + 1; // +1 for the backslash

            return new Node\LiteralNode($token->value, $startPos, $endPos);
        }

        if ($this->match(TokenType::T_CHAR_TYPE)) {
            $token = $this->previous();
            $endPos = $startPos + mb_strlen($token->value) + 1; // +1 for the backslash

            return new Node\CharTypeNode($token->value, $startPos, $endPos);
        }

        if ($this->match(TokenType::T_DOT)) {
            return new Node\DotNode($startPos, $startPos + 1);
        }

        if ($this->match(TokenType::T_ANCHOR)) {
            $token = $this->previous();
            $endPos = $startPos + mb_strlen($token->value);

            return new Node\AnchorNode($token->value, $startPos, $endPos);
        }

        if ($this->match(TokenType::T_ASSERTION)) {
            $token = $this->previous();
            $endPos = $startPos + mb_strlen($token->value) + 1;

            return new Node\AssertionNode($token->value, $startPos, $endPos);
        }

        if ($this->match(TokenType::T_BACKREF)) {
            $token = $this->previous();
            $endPos = $startPos + mb_strlen($token->value);

            return new Node\BackrefNode($token->value, $startPos, $endPos);
        }

        if ($this->match(TokenType::T_G_REFERENCE)) {
            return $this->parseGReference($startPos);
        }

        if ($this->match(TokenType::T_UNICODE)) {
            $token = $this->previous();
            $endPos = $startPos + mb_strlen($token->value);

            return new Node\UnicodeNode($token->value, $startPos, $endPos);
        }

        if ($this->match(TokenType::T_OCTAL)) {
            $token = $this->previous();
            $endPos = $startPos + mb_strlen($token->value);

            return new Node\OctalNode($token->value, $startPos, $endPos);
        }

        if ($this->match(TokenType::T_OCTAL_LEGACY)) {
            $token = $this->previous();
            $endPos = $startPos + mb_strlen($token->value) + 1;

            return new Node\OctalLegacyNode($token->value, $startPos, $endPos);
        }

        if ($this->match(TokenType::T_UNICODE_PROP)) {
            $token = $this->previous();
            // Calculate end pos based on original syntax (\p{L} vs \pL)
            $len = 2 + mb_strlen($token->value); // \p or \P + value
            if (mb_strlen($token->value) > 1 || str_starts_with($token->value, '^')) {
                $len += 2; // for {}
            }
            $endPos = $startPos + $len;

            return new Node\UnicodePropNode($token->value, $startPos, $endPos);
        }

        if ($this->match(TokenType::T_KEEP)) {
            return new Node\KeepNode($startPos, $startPos + 2); // \K
        }

        if ($this->match(TokenType::T_GROUP_OPEN)) {
            $startToken = $this->previous();
            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');
            $endPos = $endToken->position + 1;

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_CAPTURING, null, null, $startToken->position, $endPos);
        }

        if ($this->match(TokenType::T_GROUP_MODIFIER_OPEN)) {
            return $this->parseGroupModifier();
        }

        if ($this->match(TokenType::T_CHAR_CLASS_OPEN)) {
            return $this->parseCharClass();
        }

        if ($this->match(TokenType::T_PCRE_VERB)) {
            $token = $this->previous();
            $endPos = $startPos + mb_strlen($token->value) + 3; // +3 for "(*)"

            return new Node\PcreVerbNode($token->value, $startPos, $endPos);
        }

        // Special case: quantifier without target
        if ($this->check(TokenType::T_QUANTIFIER)) {
            throw new ParserException(\sprintf('Quantifier without target at position %d', $this->current()->position));
        }

        // @codeCoverageIgnoreStart
        $val = $this->current()->value;
        $type = $this->current()->type->value;

        throw new ParserException(\sprintf('Unexpected token "%s" (%s) at position %d.', $val, $type, $startPos));
        // @codeCoverageIgnoreEnd
    }

    private function parseGReference(int $startPos): Node\NodeInterface
    {
        $token = $this->previous();
        $value = $token->value;
        $endPos = $startPos + mb_strlen($value);

        // \g{N} or \gN (numeric, incl. relative) -> Backreference
        if (preg_match('/^\\\\g\{?([0-9+-]+)\}?$/', $value, $m)) {
            return new Node\BackrefNode($value, $startPos, $endPos);
        }

        // \g<name> or \g{name} (non-numeric) -> Subroutine
        if (preg_match('/^\\\\g<(\w+)>$/', $value, $m) || preg_match('/^\\\\g\{(\w+)\}$/', $value, $m)) {
            return new Node\SubroutineNode($m[1], 'g', $startPos, $endPos);
        }

        throw new ParserException(\sprintf('Invalid \g reference syntax: %s at position %d', $value, $token->position));
    }

    private function parseComment(): Node\CommentNode
    {
        $startToken = $this->previous(); // (?#
        $startPos = $startToken->position;

        $comment = '';
        while (!$this->isAtEnd() && !$this->check(TokenType::T_GROUP_CLOSE)) {
            $token = $this->current();
            $comment .= $this->reconstructTokenValue($token);
            $this->advance();
        }

        $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected ) to close comment');
        $endPos = $endToken->position + 1;

        return new Node\CommentNode($comment, $startPos, $endPos);
    }

    private function reconstructTokenValue(Token $token): string
    {
        return match ($token->type) {
            // Simple literals
            TokenType::T_LITERAL, TokenType::T_NEGATION, TokenType::T_RANGE, TokenType::T_DOT,
            TokenType::T_GROUP_OPEN, TokenType::T_GROUP_CLOSE, TokenType::T_CHAR_CLASS_OPEN, TokenType::T_CHAR_CLASS_CLOSE,
            TokenType::T_QUANTIFIER, TokenType::T_ALTERNATION, TokenType::T_ANCHOR => $token->value,

            // Types that had a \ stripped
            TokenType::T_CHAR_TYPE, TokenType::T_ASSERTION, TokenType::T_KEEP, TokenType::T_OCTAL_LEGACY,
            TokenType::T_LITERAL_ESCAPED => '\\'.$token->value,

            // Types that kept their \
            TokenType::T_BACKREF, TokenType::T_G_REFERENCE, TokenType::T_UNICODE, TokenType::T_OCTAL => $token->value,

            // Complex re-assembly
            TokenType::T_UNICODE_PROP => str_starts_with($token->value, '{') ? '\p'.$token->value : ((mb_strlen($token->value) > 1 || str_starts_with($token->value, '^')) ? '\p{'.$token->value.'}' : '\p'.$token->value),
            TokenType::T_POSIX_CLASS => '[[:'.$token->value.':]]',
            TokenType::T_PCRE_VERB => '(*'.$token->value.')',
            TokenType::T_GROUP_MODIFIER_OPEN => '(?',
            TokenType::T_COMMENT_OPEN => '(?#',
            TokenType::T_QUOTE_MODE_START => '\Q',
            TokenType::T_QUOTE_MODE_END => '\E',

            // Should not be encountered here
            TokenType::T_EOF => '',
        };
    }

    private function parseGroupModifier(): Node\NodeInterface
    {
        $startToken = $this->previous(); // (?
        $startPos = $startToken->position;

        // 1. Check for Python-style 'P' groups
        $pPos = $this->current()->position;
        if ($this->matchLiteral('P')) {
            return $this->parsePythonGroup($startPos, $pPos);
        }

        // 2. Check for standard lookarounds and named groups
        if ($this->matchLiteral('<')) {
            return $this->parseStandardGroup($startPos);
        }

        // 3. Check for conditional (?(...)
        $isConditionalWithModifier = null;
        if ($this->match(TokenType::T_GROUP_MODIFIER_OPEN)) {
            $isConditionalWithModifier = true;
        } elseif ($this->match(TokenType::T_GROUP_OPEN)) {
            $isConditionalWithModifier = false;
        }

        if (null !== $isConditionalWithModifier) {
            return $this->parseConditional($startPos, $isConditionalWithModifier);
        }

        // 4. Check for Subroutines
        if ($this->matchLiteral('&')) { // (?&name)
            $name = $this->parseSubroutineName();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected ) to close subroutine call');

            return new Node\SubroutineNode($name, '&', $startPos, $endToken->position + 1);
        }

        if ($this->matchLiteral('R')) { // (?R)
            if ($this->check(TokenType::T_GROUP_CLOSE)) {
                $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

                return new Node\SubroutineNode('R', '', $startPos, $endToken->position + 1);
            }
            $this->stream->rewind(1); // Rewind 'R'
        }

        // Check for (?1), (?-1), (?0)
        if ($subroutine = $this->parseNumericSubroutine($startPos)) {
            return $subroutine;
        }

        // 5. Check for simple non-capturing, lookaheads, atomic, branch reset
        if ($this->matchLiteral(':')) {
            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_NON_CAPTURING, null, null, $startPos, $endToken->position + 1);
        }
        if ($this->matchLiteral('=')) {
            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_LOOKAHEAD_POSITIVE, null, null, $startPos, $endToken->position + 1);
        }
        if ($this->matchLiteral('!')) {
            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_LOOKAHEAD_NEGATIVE, null, null, $startPos, $endToken->position + 1);
        }
        if ($this->matchLiteral('>')) {
            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_ATOMIC, null, null, $startPos, $endToken->position + 1);
        }
        if ($this->match(TokenType::T_ALTERNATION)) {
            // Branch reset group (?|...)
            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_BRANCH_RESET, null, null, $startPos, $endToken->position + 1);
        }

        // 6. Inline flags
        return $this->parseInlineFlags($startPos);
    }

    private function parsePythonGroup(int $startPos, int $pPos): Node\NodeInterface
    {
        // Check for (?P'name'...) or (?P"name"...)
        if ($this->checkLiteral("'") || $this->checkLiteral('"')) {
            $quote = $this->current()->value;
            $this->advance();

            // Consume T_LITERAL tokens to build the name character by character
            $name = '';
            while (!$this->isAtEnd() && !$this->checkLiteral($quote)) {
                if ($this->check(TokenType::T_LITERAL)) {
                    $name .= $this->current()->value;
                    $this->advance();
                } else {
                    throw new ParserException(
                        \sprintf('Unexpected token in group name at position %d', $this->current()->position));
                }
            }

            if ('' === $name) {
                throw new ParserException(\sprintf('Expected group name at position %d', $this->current()->position));
            }

            if (!$this->checkLiteral($quote)) {
                throw new ParserException(
                    \sprintf('Expected closing quote %s at position %d', $quote, $this->current()->position));
            }
            $this->advance();

            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_NAMED, $name, null, $startPos, $endToken->position + 1);
        }

        if ($this->matchLiteral('<')) { // (?P<name>...)
            $name = $this->parseGroupName();
            $this->consumeLiteral('>', 'Expected > after group name');
            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_NAMED, $name, null, $startPos, $endToken->position + 1);
        }

        if ($this->matchLiteral('>')) { // (?P>name) subroutine
            $name = $this->parseSubroutineName();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected ) to close subroutine call');

            return new Node\SubroutineNode($name, 'P>', $startPos, $endToken->position + 1);
        }

        if ($this->matchLiteral('=')) {
            throw new ParserException('Backreferences (?P=name) are not supported yet.');
        }

        throw new ParserException(\sprintf('Invalid syntax after (?P at position %d', $pPos));
    }

    private function parseStandardGroup(int $startPos): Node\NodeInterface
    {
        if ($this->matchLiteral('=')) { // (?<=...)
            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_LOOKBEHIND_POSITIVE, null, null, $startPos, $endToken->position + 1);
        }
        if ($this->matchLiteral('!')) { // (?<!...)
            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_LOOKBEHIND_NEGATIVE, null, null, $startPos, $endToken->position + 1);
        }
        // (?<name>...)
        $name = $this->parseGroupName();
        $this->consumeLiteral('>', 'Expected > after group name');
        $expr = $this->parseAlternation();
        $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

        return new Node\GroupNode($expr, Node\GroupType::T_GROUP_NAMED, $name, null, $startPos, $endToken->position + 1);
    }

    private function parseNumericSubroutine(int $startPos): ?Node\SubroutineNode
    {
        $num = '';
        if ($this->matchLiteral('-')) {
            $num = '-';
        }
        if ($this->check(TokenType::T_LITERAL) && ctype_digit($this->current()->value)) {
            $num .= $this->current()->value;
            $this->advance();
            $num .= $this->consumeWhile(fn (string $c) => ctype_digit($c));

            if ($this->check(TokenType::T_GROUP_CLOSE)) {
                $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

                return new Node\SubroutineNode($num, '', $startPos, $endToken->position + 1);
            }
            $this->stream->rewind(mb_strlen($num));
        } elseif ('-' === $num) {
            $this->stream->rewind(1);
        }

        return null;
    }

    private function parseInlineFlags(int $startPos): Node\NodeInterface
    {
        // Support all PCRE2 flags including n (NO_AUTO_CAPTURE), r (unicode restricted), and ^ (unset)
        // Handle ^ (T_ANCHOR) at the start - it means "unset all flags" in PCRE2
        $flags = '';
        if ($this->check(TokenType::T_ANCHOR) && '^' === $this->current()->value) {
            $flags = '^';
            $this->advance();
        }
        $flags .= $this->consumeWhile(fn (string $c) => (bool) preg_match('/^[imsxADSUXJnr-]+$/', $c));
        if ('' !== $flags) {
            $expr = null;
            if ($this->matchLiteral(':')) {
                $expr = $this->parseAlternation();
            }
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            if (null === $expr) {
                $currentPos = $this->previous()->position;
                $expr = new Node\LiteralNode('', $currentPos, $currentPos);
            }

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_INLINE_FLAGS, null, $flags, $startPos, $endToken->position + 1);
        }

        throw new ParserException(\sprintf('Invalid group modifier syntax at position %d', $startPos));
    }

    private function parseConditional(int $startPos, bool $isModifier): Node\ConditionalNode|Node\DefineNode
    {
        if ($isModifier) {
            // Inline Lookaround condition
            $conditionStartPos = $this->previous()->position;
            $condition = $this->parseLookaroundCondition($conditionStartPos);
        } else {
            $condition = $this->parseConditionalCondition();
            $this->consume(TokenType::T_GROUP_CLOSE, 'Expected ) after condition');
        }

        $yes = $this->parseAlternation();

        // Special case: (?(DEFINE)...) creates a DefineNode instead of ConditionalNode
        if ($condition instanceof Node\AssertionNode && 'DEFINE' === $condition->value) {
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');
            $endPos = $endToken->position + 1;

            return new Node\DefineNode($yes, $startPos, $endPos);
        }

        // Note: The "no" branch (ELSE) is implicitly handled by parseAlternation returning an AlternationNode.
        // If the "yes" branch is an alternation (a|b), then "b" is the ELSE branch.
        // However, if parseAlternation returns a single SequenceNode, then the "no" branch is empty.

        // Correct interpretation:
        // (?(cond)yes|no) -> parseAlternation will return an AlternationNode if '|' exists.
        // But wait! parseAlternation consumes EVERYTHING until ')' or EOF.
        // So if we have (?(cond)A|B), 'yes' variable will hold Alternation(A, B).
        // We need to split it manually?
        // No, the standard Parser logic (inherited) assigns 'no' to an empty LiteralNode.
        // If 'yes' is an AlternationNode, the visitor/compiler handles the split.
        // Let's stick to the original logic to be safe:

        $currentPos = $this->current()->position;
        $no = new Node\LiteralNode('', $currentPos, $currentPos);

        $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');
        $endPos = $endToken->position + 1;

        return new Node\ConditionalNode($condition, $yes, $no, $startPos, $endPos);
    }

    private function parseLookaroundCondition(int $startPos): Node\NodeInterface
    {
        if ($this->matchLiteral('=')) {
            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_LOOKAHEAD_POSITIVE, null, null, $startPos, $endToken->position);
        }
        if ($this->matchLiteral('!')) {
            $expr = $this->parseAlternation();
            $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

            return new Node\GroupNode($expr, Node\GroupType::T_GROUP_LOOKAHEAD_NEGATIVE, null, null, $startPos, $endToken->position);
        }
        if ($this->matchLiteral('<')) {
            // @phpstan-ignore-next-line if.alwaysFalse (false positive: position advanced after matching '<')
            if ($this->matchLiteral('=')) {
                $expr = $this->parseAlternation();
                $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

                return new Node\GroupNode($expr, Node\GroupType::T_GROUP_LOOKBEHIND_POSITIVE, null, null, $startPos, $endToken->position);
            }
            // @phpstan-ignore-next-line if.alwaysFalse (false positive: position advanced after matching '<')
            if ($this->matchLiteral('!')) {
                $expr = $this->parseAlternation();
                $endToken = $this->consume(TokenType::T_GROUP_CLOSE, 'Expected )');

                return new Node\GroupNode($expr, Node\GroupType::T_GROUP_LOOKBEHIND_NEGATIVE, null, null, $startPos, $endToken->position);
            }
        }

        throw new ParserException('Invalid conditional condition at position '.$startPos);
    }

    private function parseConditionalCondition(): Node\NodeInterface
    {
        $startPos = $this->current()->position;

        // This handles the PCRE feature where (?(DEFINE)...) allows defining subroutines
        // without matching them immediately.
        // We need to check for 'DEFINE' by peeking at multiple tokens since the lexer
        // tokenizes each character separately.
        if ($this->check(TokenType::T_LITERAL) && 'D' === $this->current()->value) {
            $savedPos = $this->stream->getPosition();
            $word = '';
            while ($this->check(TokenType::T_LITERAL) && ctype_alpha($this->current()->value)) {
                $word .= $this->current()->value;
                $this->advance();
            }
            if ('DEFINE' === $word && $this->check(TokenType::T_GROUP_CLOSE)) {
                return new Node\AssertionNode('DEFINE', $startPos, $this->current()->position);
            }
            // Not DEFINE, restore position
            $this->stream->setPosition($savedPos);
        }

        if ($this->check(TokenType::T_LITERAL) && ctype_digit($this->current()->value)) {
            $this->advance();
            $num = (string) ($this->previous()->value.$this->consumeWhile(fn (string $c) => ctype_digit($c)));

            return new Node\BackrefNode($num, $startPos, $this->current()->position);
        }

        if ($this->matchLiteral('<') || $this->matchLiteral('{')) {
            $open = $this->previous()->value;
            $name = $this->parseGroupName();
            $close = '<' === $open ? '>' : '}';
            $this->consumeLiteral($close, "Expected $close after condition name");

            return new Node\BackrefNode($name, $startPos, $this->current()->position);
        }

        if ($this->matchLiteral('R')) {
            return new Node\SubroutineNode('R', '', $startPos, $this->current()->position);
        }

        if ($this->matchLiteral('?')) {
            // Lookaround condition inside (?(...))
            return $this->parseLookaroundCondition($startPos);
        }

        // Bare name check (for conditions like (?(name)...))
        if ($this->check(TokenType::T_LITERAL)) {
            $savedPos = $this->stream->getPosition();
            $name = '';
            while ($this->check(TokenType::T_LITERAL) && !$this->checkLiteral(')') && !$this->isAtEnd()) {
                $name .= $this->current()->value;
                $this->advance();
            }
            if ('' !== $name && $this->check(TokenType::T_GROUP_CLOSE)) {
                return new Node\BackrefNode($name, $startPos, $this->current()->position);
            }
            $this->stream->setPosition($savedPos);
        }

        $condition = $this->parseAtom();

        if (!($condition instanceof Node\BackrefNode || $condition instanceof Node\GroupNode
              || $condition instanceof Node\AssertionNode || $condition instanceof Node\SubroutineNode)) {
            throw new ParserException(
                \sprintf('Invalid conditional construct at position %d. Condition must be a group reference, lookaround, or (DEFINE).', $startPos));
        }

        return $condition;
    }

    private function parseGroupName(): string
    {
        $name = '';
        while (!$this->checkLiteral('>') && !$this->checkLiteral('}') && !$this->isAtEnd()) {
            if ($this->check(TokenType::T_LITERAL) || $this->check(TokenType::T_LITERAL_ESCAPED)) {
                $name .= $this->current()->value;
                $this->advance();
            } else {
                throw new ParserException(\sprintf('Unexpected token "%s" in group name', $this->current()->value));
            }
        }

        if ('' === $name) {
            throw new ParserException(\sprintf('Expected group name at position %d', $this->current()->position));
        }

        return $name;
    }

    private function parseCharClass(): Node\CharClassNode
    {
        $startToken = $this->previous();
        $startPos = $startToken->position;
        $isNegated = $this->match(TokenType::T_NEGATION);
        $parts = [];

        while (!$this->check(TokenType::T_CHAR_CLASS_CLOSE) && !$this->isAtEnd()) {
            // Silent tokens inside char class
            if ($this->match(TokenType::T_QUOTE_MODE_START) || $this->match(TokenType::T_QUOTE_MODE_END)) {
                continue;
            }
            $parts[] = $this->parseCharClassPart();
        }

        $endToken = $this->consume(TokenType::T_CHAR_CLASS_CLOSE, 'Expected "]" to close character class');

        return new Node\CharClassNode($parts, $isNegated, $startPos, $endToken->position + 1);
    }

    private function parseCharClassPart(): Node\NodeInterface
    {
        $startToken = $this->current();
        $startPos = $startToken->position;
        $startNode = null;

        // Simplified matching logic for char class parts
        if ($this->match(TokenType::T_LITERAL) || $this->match(TokenType::T_LITERAL_ESCAPED)) {
            $token = $this->previous();
            // Check for range validity
            // +1 if escaped
            $endPos = $startPos + mb_strlen($token->value) + (TokenType::T_LITERAL_ESCAPED === $token->type ? 1 : 0);
            $startNode = new Node\LiteralNode($token->value, $startPos, $endPos);
        } elseif ($this->match(TokenType::T_CHAR_TYPE)) {
            $token = $this->previous();
            $startNode = new Node\CharTypeNode($token->value, $startPos, $startPos + mb_strlen($token->value) + 1);
        } elseif ($this->match(TokenType::T_UNICODE_PROP)) {
            $token = $this->previous();
            // Basic length calc - Parser logic from original
            $len = 2 + mb_strlen($token->value) + ((mb_strlen($token->value) > 1 || str_starts_with($token->value, '^')) ? 2 : 0);
            $startNode = new Node\UnicodePropNode($token->value, $startPos, $startPos + $len);
        } elseif ($this->match(TokenType::T_UNICODE)) {
            $token = $this->previous();
            $startNode = new Node\UnicodeNode($token->value, $startPos, $startPos + mb_strlen($token->value));
        } elseif ($this->match(TokenType::T_OCTAL)) {
            $token = $this->previous();
            $startNode = new Node\OctalNode($token->value, $startPos, $startPos + mb_strlen($token->value));
        } elseif ($this->match(TokenType::T_OCTAL_LEGACY)) {
            $token = $this->previous();
            $startNode = new Node\OctalLegacyNode($token->value, $startPos, $startPos + mb_strlen($token->value) + 1);
        } elseif ($this->match(TokenType::T_RANGE)) {
            // Literal hyphen at start
            return new Node\LiteralNode($this->previous()->value, $startPos, $startPos + 1);
        } elseif ($this->match(TokenType::T_POSIX_CLASS)) {
            $token = $this->previous();
            $startNode = new Node\PosixClassNode($token->value, $startPos, $startPos + mb_strlen($token->value) + 4);
        } else {
            throw new ParserException(
                \sprintf('Unexpected token "%s" in character class at position %d.', $this->current()->value, $this->current()->position));
        }

        // Check for Range
        if ($this->match(TokenType::T_RANGE)) {
            if ($this->check(TokenType::T_CHAR_CLASS_CLOSE)) {
                // Trailing hyphen
                $this->stream->rewind(1);

                return $startNode;
            }

            // For simplicity, we call parseCharClassPart recursively for the end node,
            // but we need to ensure it returns a simple node, not a range.
            // In this grammar, ranges don't chain (a-b-c is invalid or literals).
            // We manually parse the end node to avoid recursion loop.

            $endToken = $this->current();
            $endNodeStartPos = $endToken->position;

            // Re-using the logic above is tricky without recursion.
            // Let's assume simple structure: a-z.
            // We call parseCharClassPart again.
            $endNode = $this->parseCharClassPart();

            // Note: Original code handled this inline.
            return new Node\RangeNode($startNode, $endNode, $startPos, $endNode->getEndPosition());
        }

        return $startNode;
    }

    private function parseSubroutineName(): string
    {
        $name = '';
        while (!$this->check(TokenType::T_GROUP_CLOSE) && !$this->isAtEnd()) {
            if ($this->check(TokenType::T_LITERAL) || $this->check(TokenType::T_LITERAL_ESCAPED)) {
                $char = $this->current()->value;
                if (!preg_match('/^[a-zA-Z0-9_]$/', $char)) {
                    throw new ParserException('Unexpected token in subroutine name: '.$char);
                }
                $name .= $char;
                $this->advance();
            } else {
                throw new ParserException('Unexpected token in subroutine name: '.$this->current()->value);
            }
        }
        if ('' === $name) {
            throw new ParserException('Expected subroutine name at position '.$this->current()->position);
        }

        return $name;
    }

    private function match(TokenType $type): bool
    {
        if ($this->check($type)) {
            $this->advance();

            return true;
        }

        return false;
    }

    private function matchLiteral(string $value): bool
    {
        if ($this->checkLiteral($value)) {
            $this->advance();

            return true;
        }

        return false;
    }

    private function checkLiteral(string $value): bool
    {
        if ($this->isAtEnd()) {
            return false;
        }
        $token = $this->current();

        return TokenType::T_LITERAL === $token->type && $token->value === $value;
    }

    private function consume(TokenType $type, string $error): Token
    {
        if ($this->check($type)) {
            $token = $this->current();
            $this->advance();

            return $token;
        }
        $at = $this->isAtEnd() ? 'end of input' : 'position '.$this->current()->position;

        throw new ParserException($error.' at '.$at.' (found '.$this->current()->type->value.')');
    }

    private function consumeLiteral(string $value, string $error): Token
    {
        if ($this->checkLiteral($value)) {
            $token = $this->current();
            $this->advance();

            return $token;
        }
        $at = $this->isAtEnd() ? 'end of input' : 'position '.$this->current()->position;

        throw new ParserException($error.' at '.$at.' (found '.$this->current()->type->value.' with value '.$this->current()->value.')');
    }

    private function check(TokenType $type): bool
    {
        if ($this->isAtEnd()) {
            return TokenType::T_EOF === $type;
        }

        return $this->current()->type === $type;
    }

    private function advance(): void
    {
        if (!$this->isAtEnd()) {
            $this->stream->next();
        }
    }

    private function isAtEnd(): bool
    {
        return TokenType::T_EOF === $this->current()->type;
    }

    private function current(): Token
    {
        return $this->stream->current();
    }

    private function previous(): Token
    {
        return $this->stream->peek(-1);
    }

    private function consumeWhile(callable $predicate): string
    {
        $value = '';
        while (!$this->isAtEnd() && $this->check(TokenType::T_LITERAL) && $predicate($this->current()->value)) {
            $value .= $this->current()->value;
            $this->advance();
        }

        return $value;
    }
}
