<?php

declare(strict_types=1);

/*
 * This file is part of the RegexParser package.
 *
 * (c) Younes ENNAJI <younes.ennaji.pro@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace RegexParser;

/**
 * Represents a single, indivisible unit of a regular expression.
 *
 * Purpose: This class is a simple Data Transfer Object (DTO) that holds the
 * information for a token generated by the `Lexer`. Think of tokens as the "words"
 * of a regex. The `Lexer` breaks the raw regex string into a stream of these
 * `Token` objects, which the `Parser` then assembles into a meaningful structure (the AST).
 * This object is immutable to ensure data integrity throughout the parsing process.
 */
readonly class Token
{
    /**
     * Creates a new Token instance.
     *
     * @param TokenType $type The category of the token, such as a literal, quantifier, or group opener.
     *                        This is the most important piece of information for the parser.
     * @param string $value The exact substring from the original pattern that this token represents
     *                      (e.g., "a", "*", "\d").
     * @param int $position The zero-based character offset where this token's value begins in the
     *                      original, full regex pattern. This is crucial for error reporting.
     */
    public function __construct(
        public TokenType $type,
        public string $value,
        public int $position,
    ) {}
}
