<?php

declare(strict_types=1);

/*
 * This file is part of the RegexParser package.
 *
 * (c) Younes ENNAJI <younes.ennaji.pro@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace RegexParser;

/**
 * Represents a single, indivisible unit of a regular expression.
 *
 * Purpose: This class is a simple Data Transfer Object (DTO) that holds the
 * information for a token generated by the `Lexer`. Think of tokens as the "words"
 * of a regex. The `Lexer` breaks the raw regex string into a stream of these
 * `Token` objects, which the `Parser` then assembles into a meaningful structure (the AST).
 * This object is immutable to ensure data integrity throughout the parsing process.
 */
readonly class Token
{
    /**
     * Creates a new, immutable Token instance.
     *
     * Purpose: This constructor initializes a token, which is a fundamental, indivisible
     * unit of a regular expression. The `Lexer` produces a stream of these tokens, and
     * the `Parser` consumes them to build the Abstract Syntax Tree (AST). As a contributor,
     * you can think of this as a simple, read-only data structure that carries information
     * from the lexer to the parser.
     *
     * @param TokenType $type     The category of the token (e.g., `T_LITERAL`, `T_QUANTIFIER`). This enum
     *                            value is the primary piece of information the `Parser` uses to make
     *                            decisions.
     * @param string    $value    The exact substring from the original pattern that this token represents
     *                            (e.g., "a", "*", "\d"). This preserves the original source for
     *                            compilation and analysis.
     * @param int       $position The zero-based byte offset where this token's value begins in the
     *                            original pattern string. This is crucial for providing accurate
     *                            error messages.
     */
    public function __construct(
        public TokenType $type,
        public string $value,
        public int $position,
    ) {}
}
