<?php

declare(strict_types=1);

/*
 * This file is part of the RegexParser package.
 *
 * (c) Younes ENNAJI <younes.ennaji.pro@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace RegexParser\Cache;

use Psr\Cache\CacheItemPoolInterface;
use RegexParser\Node\RegexNode;

/**
 * PSR-6 bridge for AST caching.
 *
 * This adapter lets you plug a PSR-6 cache pool into the RegexParser cache
 * system. The Regex service passes a compiled cache payload string
 * (generated by {@see \RegexParser\Regex::compileCachePayload()}); this
 * adapter evaluates that payload once and stores the resulting RegexNode
 * instance directly in the pool so that subsequent reads are fast and
 * type-safe.
 */
final readonly class PsrCacheAdapter implements RemovableCacheInterface
{
    public function __construct(
        private CacheItemPoolInterface $pool,
        private string $prefix = 'regex_',
        private ?\Closure $keyFactory = null
    ) {}

    public function generateKey(string $regex): string
    {
        if (null !== $this->keyFactory) {
            $custom = ($this->keyFactory)($regex);

            return $this->prefix.(\is_string($custom) ? $custom : hash('sha256', serialize($custom)));
        }

        return $this->prefix.hash('sha256', $regex);
    }

    public function write(string $key, string $content): void
    {
        $item = $this->pool->getItem($key);

        $value = $this->decodePayload($content);
        $item->set($value ?? $content);

        $this->pool->save($item);
    }

    public function load(string $key): mixed
    {
        $item = $this->pool->getItem($key);

        return $item->isHit() ? $item->get() : null;
    }

    public function getTimestamp(string $key): int
    {
        // PSR-6 does not expose timestamps; return 0 (unknown).
        return 0;
    }

    public function clear(?string $regex = null): void
    {
        if (null !== $regex) {
            $this->pool->deleteItem($this->generateKey($regex));

            return;
        }

        $this->pool->clear();
    }

    /**
     * Decodes the compiled cache payload string into a RegexNode instance.
     *
     * The Regex service passes a small PHP script generated by
     * {@see \RegexParser\Regex::compileCachePayload()}. For PSR-6 caches we
     * execute this script once and store the resulting AST object directly
     * in the pool so that subsequent reads return a RegexNode instead of
     * the raw payload string.
     */
    private function decodePayload(string $content): ?RegexNode
    {
        $code = ltrim($content);

        if (str_starts_with($code, '<?php')) {
            $code = substr($code, 5);
        }

        try {
            $result = eval($code);

            return $result instanceof RegexNode ? $result : null;
        } catch (\Throwable) {
            // If anything goes wrong we just fall back to storing the raw payload.
            return null;
        }
    }
}
