<?php

declare(strict_types=1);

/*
 * This file is part of the RegexParser package.
 *
 * (c) Younes ENNAJI <younes.ennaji.pro@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace RegexParser\Cache;

use Psr\SimpleCache\CacheInterface;
use RegexParser\Node\RegexNode;

/**
 * PSR-16 bridge for AST caching.
 *
 * This adapter lets you plug a PSR-16 cache implementation into the
 * RegexParser cache system. It receives the compiled cache payload string
 * from the Regex service and stores the decoded RegexNode instance so
 * later reads can return the AST directly.
 */
final readonly class PsrSimpleCacheAdapter implements RemovableCacheInterface
{
    public function __construct(
        private CacheInterface $cache,
        private string $prefix = 'regex_',
        private ?\Closure $keyFactory = null
    ) {}

    public function generateKey(string $regex): string
    {
        if (null !== $this->keyFactory) {
            $custom = ($this->keyFactory)($regex);

            return $this->prefix.(\is_string($custom) ? $custom : hash('sha256', serialize($custom)));
        }

        return $this->prefix.hash('sha256', $regex);
    }

    public function write(string $key, string $content): void
    {
        $value = $this->decodePayload($content);

        $this->cache->set($key, $value ?? $content);
    }

    public function load(string $key): mixed
    {
        $value = $this->cache->get($key);

        return $value ?? null;
    }

    public function getTimestamp(string $key): int
    {
        return 0;
    }

    public function clear(?string $regex = null): void
    {
        if (null !== $regex) {
            $this->cache->delete($this->generateKey($regex));

            return;
        }

        $this->cache->clear();
    }

    /**
     * Decodes the compiled cache payload string into a RegexNode instance.
     *
     * The Regex service passes a small PHP script generated by
     * {@see \RegexParser\Regex::compileCachePayload()}. For PSR-16 caches we
     * execute this script once and store the resulting AST object directly
     * in the cache so that subsequent reads return a RegexNode.
     */
    private function decodePayload(string $content): ?RegexNode
    {
        $code = ltrim($content);

        if (str_starts_with($code, '<?php')) {
            $code = substr($code, 5);
        }

        try {
            $result = eval($code);

            return $result instanceof RegexNode ? $result : null;
        } catch (\Throwable) {
            return null;
        }
    }
}
